spring.application.name=parkinglot_project
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/parking_lot
spring.datasource.username=postgres
spring.datasource.password=tatasky
debug=true